remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
title: Hi there. I'm Quinn Leary.
description: QA Specialist. Programmer. Cat lover.
